[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.11.0"
constraintlayout = "2.1.4"
jetbrainsKotlinJvm = "2.0.21"
nav_version = "2.9.6"
fragment = "1.5.6"
lifecycle_version = "2.9.4"
koin_version = "2.2.3"
coroutines_version = "1.10.2"
retrofit_version = "3.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle_version"}

androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "nav_version" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "nav_version" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }

insert-koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin_version"}
insert-koin-androidx-viewmodel = { module = "io.insert-koin:koin-androidx-viewmodel", version.ref = "koin_version" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines_version" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines_version" }

retrofit = { module = "com.squareup.retrofit2:retrofit",version.ref = "retrofit_version"}
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson",version.ref = "retrofit_version"}
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars",version.ref = "retrofit_version"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

